/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.Pedido;
import fatec.poo.model.Pessoa;
import fatec.poo.model.Produto;
import java.util.ArrayList;

/**
 *
 * @author gusta
 */
public class GuiMenu extends javax.swing.JFrame {

    /**
     * Creates new form GuiMenu
     */
    public GuiMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitCliente = new javax.swing.JMenuItem();
        mitVendedores = new javax.swing.JMenuItem();
        mitProdutos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mitSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mitEmitirPedido = new javax.swing.JMenuItem();
        mitConsultaCliPed = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Vendas");

        jMenuBar1.setName(""); // NOI18N

        jMenu1.setText("Cadastros");

        mitCliente.setText("Clientes");
        mitCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mitCliente);

        mitVendedores.setText("Vendedores");
        mitVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitVendedoresActionPerformed(evt);
            }
        });
        jMenu1.add(mitVendedores);

        mitProdutos.setText("Produtos");
        mitProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(mitProdutos);
        jMenu1.add(jSeparator1);

        mitSair.setText("Sair");
        mitSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitSairActionPerformed(evt);
            }
        });
        jMenu1.add(mitSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pedido");

        mitEmitirPedido.setText("Emitir Pedido");
        mitEmitirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitEmitirPedidoActionPerformed(evt);
            }
        });
        jMenu2.add(mitEmitirPedido);

        mitConsultaCliPed.setText("Consultar Cliente x Pedidos");
        mitConsultaCliPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitConsultaCliPedActionPerformed(evt);
            }
        });
        jMenu2.add(mitConsultaCliPed);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 699, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitClienteActionPerformed
        
        //cria uma instancia da classe guicliente e a torna visível
        //passamos como parametro o ponteiro do arraylist cadCliVend
        //ou seja
        //quando fazemos alguma alteração no array presente dentro da classe
        //GuiCliente, estamos alterando diretamente o arraylist cadCliVend
        new GuiCliente(cadCliVend).setVisible(true);        
    }//GEN-LAST:event_mitClienteActionPerformed

    private void mitSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitSairActionPerformed
        //fecha a janela Controle de Vendas     
        this.dispose();
    }//GEN-LAST:event_mitSairActionPerformed

    private void mitVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitVendedoresActionPerformed
        //cria uma instancia da classe guivendedor e a torna visível
        new GuiVendedor(cadCliVend).setVisible(true);
    }//GEN-LAST:event_mitVendedoresActionPerformed

    private void mitProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitProdutosActionPerformed
        //cria uma instancia da classe guiproduto e a torna visível
        //parametro = arraylist criado abaixo
        new GuiProduto(cadProd).setVisible(true);
    }//GEN-LAST:event_mitProdutosActionPerformed

    private void mitEmitirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitEmitirPedidoActionPerformed
       
        new GuiEmitirPedido(emitPed, cadCliVend, cadProd).setVisible(true);
    }//GEN-LAST:event_mitEmitirPedidoActionPerformed

    private void mitConsultaCliPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitConsultaCliPedActionPerformed
        
        new GuiConsultaClientePedido(emitPed, cadCliVend).setVisible(true);
    }//GEN-LAST:event_mitConsultaCliPedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mitCliente;
    private javax.swing.JMenuItem mitConsultaCliPed;
    private javax.swing.JMenuItem mitEmitirPedido;
    private javax.swing.JMenuItem mitProdutos;
    private javax.swing.JMenuItem mitSair;
    private javax.swing.JMenuItem mitVendedores;
    // End of variables declaration//GEN-END:variables

    
    //criação dos arraylist da classe pessoa e da classe produto
    //os objetos instanciados deverão ficar salvos nos arrays abaixo
    private ArrayList<Pessoa> cadCliVend = new ArrayList<Pessoa>();
    
    private ArrayList<Produto> cadProd = new ArrayList<Produto>();
    
    private ArrayList<Pedido> emitPed = new ArrayList<Pedido>();
    

}
