/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.Produto;
import java.util.ArrayList;



/**
 *
 * @author gusta
 */
public class GuiProduto extends javax.swing.JFrame {

    /**
     * Creates new form GuiProduto
     */
    public GuiProduto(ArrayList <Produto> p) {
        
        //atribui o parametro recebido no ponteiro auxiliar criado abaixo
        prod = p;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtQtdeDisponivel = new javax.swing.JTextField();
        txtPrecoUnitario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEstoqueMinimo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Produtos");

        jLabel2.setText("Codigo");

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.setEnabled(false);
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel3.setText("Descrição");

        txtDescricao.setEnabled(false);

        jLabel4.setText("Qtde. Disponível");

        txtQtdeDisponivel.setEnabled(false);

        txtPrecoUnitario.setEnabled(false);

        jLabel5.setText("Preço Unitário");

        jLabel6.setText("Estoque Minimo");

        txtEstoqueMinimo.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtDescricao)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQtdeDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEstoqueMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtEstoqueMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtQtdeDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnIncluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        //fecha a janela Cadastro de Clientes
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        
        //pega o codigo presente no txtCodigo, transforma em int e atribui a uma variavel
        int id = Integer.parseInt(txtCodigo.getText());
        
        //Aqui começa um pouco da POG
        //Deve ter um jeito melhor de fazer isso...
        //Caso essa variavel seja true, então o for será parado
        //e o código seguirá para a estrutura de decisão abaixo (if)
        //senão após completar a busca no arraylist, seguirá direto para o else
        boolean idFound = false;
        
        //A variável INDEX foi movida
        //agora ela é global pois é utilizada também na função ALTERAR
        
        for (int i = 0; i < prod.size(); i++)
        {
            //obtem o valor do atributo codigo da classe produto, a converte e integer e a compara com o id fornecido pelo usuário
          if (Integer.parseInt(prod.get(i).getCodigo()) == id)
          {
              //encontrou ID
              idFound = true; 
              //atribui valor de i ao index
              index = i;
              //não é mais necessário executar o FOR
              break;
          
          }
        
        }
        
        //se idFound é igual a true
        if(idFound)
            
        {
            //exiba o conteudo *************************************
            //exibe conteudo do atributo descricao da classe produto no arraylist com o index = id 
            txtDescricao.setText(prod.get(index).getDescricao());
            
            //exibe conteudo do atributo quantidade de estoque da classe produto no arraylist com o index = id após convertê-la de double para string
            txtQtdeDisponivel.setText(String. valueOf(prod.get(index).getQtdeEstoque()));
            
            //exibe conteudo do atributo estoque minimo da classe produto no arraylist com o index = id após convertê-la de double para string
            txtEstoqueMinimo.setText(String. valueOf(prod.get(index).getEstoqueMinimo()));
            
            //exibe conteudo do atributo preço da classe produto no arraylist com o index = id após convertê-la de double para string
            txtPrecoUnitario.setText(String. valueOf(prod.get(index).getPreco()));
            
            //desativa botão de consulta
            btnConsultar.setEnabled(false); 
            
            //ativa o botão de alterar
            btnAlterar.setEnabled(true);
            
            //ativa o botão de excluir
            btnExcluir.setEnabled(true); 
            
            //desativa o txtcodigo
            txtCodigo.setEnabled(false);
            
            //ativa txtDescricao
            txtDescricao.setEnabled(true);
            
            //ativa txtEstoqueMinimo
            txtEstoqueMinimo.setEnabled(true);
            
            //ativa txtPrecoUnitario
            txtPrecoUnitario.setEnabled(true);
            
            //ativa quantidade disponível
            txtQtdeDisponivel.setEnabled(true);
            
        
        }
        else
        {
            //caso não tenha encontrado o elemento com o ID digitado
            //ativar o botão de inserção
            
            //desativa botão de consulta
            btnConsultar.setEnabled(false);
            
            //ativa o botão de inserção
            btnIncluir.setEnabled(true);
            
            //Isto não estava especificado na documentação
            //mas achei melhor bloquear o txtCodigo
            //pois poderia dar algum problema caso o usuário trocasse
            //o conteúdo do campo txtCodigo e colocasse um outro código já existente
            txtCodigo.setEnabled(false);
            
            //ativa txtDescricao
            txtDescricao.setEnabled(true);
            
            //ativa txtEstoqueMinimo
            txtEstoqueMinimo.setEnabled(true);
            
            //ativa txtPrecoUnitario
            txtPrecoUnitario.setEnabled(true);
            
            //ativa quantidade disponível
            txtQtdeDisponivel.setEnabled(true);

        }
        
        
        
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
          
        //pega o codigo presente no txtCodigo, transforma em int e atribui a uma variavel
        int id = Integer.parseInt(txtCodigo.getText());
        
        //para realizar a inserção, é necessário criar um objeto temporario da classe Produto
        //A classe produto tem como parametros de entrada o código (String) e a descrição (String)
        Produto prodtemp = new Produto(String. valueOf(id), txtDescricao.getText());

        //insere o conteúdo do campo txtEstoque Minimo no objeto da classe produto
        prodtemp.setEstoqueMinimo(Double.parseDouble(txtEstoqueMinimo.getText()));
        
        //insere o conteúdo do campo txtPrecoUnitario Minimo no objeto da classe produto
        prodtemp.setPreco(Double.parseDouble(txtPrecoUnitario.getText()));
        
        //insere o conteúdo do campo txtQtdeDisponivel no objeto da classe produto
        prodtemp.setQtdeEstoque(Double.parseDouble(txtQtdeDisponivel.getText()));
        
        //para finalizar, adicionamos o objeto temporario em nosso ArrayList
        prod.add(prodtemp);
        
        //****Como a inserção já foi realizada, então voltaremos o form ao seu estado inicial****
        returnFormToSearchState();
        
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        
        //agora vamos alterar os dados 
        
        //pega o codigo presente no txtCodigo, transforma em int e atribui a uma variavel
        int id = Integer.parseInt(txtCodigo.getText());
        
        //para realizar a alteração, é necessário criar um objeto temporario da classe Produto
        //A classe produto tem como parametros de entrada o código (String) e a descrição (String)
        Produto prodtemp = new Produto(String. valueOf(id), txtDescricao.getText());
        
        //insere o conteúdo do campo txtEstoque Minimo no objeto da classe produto
        prodtemp.setEstoqueMinimo(Double.parseDouble(txtEstoqueMinimo.getText()));
        
        //insere o conteúdo do campo txtPrecoUnitario Minimo no objeto da classe produto
        prodtemp.setPreco(Double.parseDouble(txtPrecoUnitario.getText()));
        
        //insere o conteúdo do campo txtQtdeDisponivel no objeto da classe produto
        prodtemp.setQtdeEstoque(Double.parseDouble(txtQtdeDisponivel.getText()));
        
        //pra finalizar utilizamos o arraylist.set(index, valor)
        prod.set(index, prodtemp);
        
        
        //****Como a alteração já foi realizada, então voltaremos o form ao seu estado inicial****
        returnFormToSearchState();
            
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        //utilizaremos a função remove do arraylist juntamente com a variável index
        prod.remove(index);

        //****Como a exclusão já foi realizada, então voltaremos o form ao seu estado inicial****
        returnFormToSearchState();
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void returnFormToSearchState() //Função criada exclusivamente para retornar o form ao estado inicial
    {
        
        //desativa botão alterar
        btnAlterar.setEnabled(false);
        //desativa botão excluir
        btnExcluir.setEnabled(false);
        
    //ativa botão de consulta
            btnConsultar.setEnabled(true);
            
            //desativa o botão de inserção
            btnIncluir.setEnabled(false);
            
            //ativa botão de codigo
            txtCodigo.setEnabled(true);
            
            //limpa txtCodigo
            txtCodigo.setText(null);
            
            //desativa txtDescricao
            txtDescricao.setEnabled(false);
            
            //limpa txtDescricao
            txtDescricao.setText(null);
            
            //desativa txtEstoqueMinimo
            txtEstoqueMinimo.setEnabled(false);
            
             //limpa txtEstoqueMinimo
            txtEstoqueMinimo.setText(null);
            
            //desativa txtPrecoUnitario
            txtPrecoUnitario.setEnabled(false);
            
            //limpa txtPrecoUnitario
            txtPrecoUnitario.setText(null);
            
            //desativa quantidade disponível
            txtQtdeDisponivel.setEnabled(false);
            
            //limpa txtQtdeDisponivel
            txtQtdeDisponivel.setText(null);
    
    }
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //Não precisa mais
                //new GuiProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtEstoqueMinimo;
    private javax.swing.JTextField txtPrecoUnitario;
    private javax.swing.JTextField txtQtdeDisponivel;
    // End of variables declaration//GEN-END:variables

    //criação do ponteiro auxiliar
    private ArrayList <Produto> prod;
    
    //essa variavel guarda o index 
    private int index = 0;

}
